#!/usr/bin/env bash
# Remove Harbor and put back what install.sh moved aside.
#   - files installed by Harbor are removed only if they are still Harbor's (a link into the repo,
#     or an unmodified copy); anything you edited is left in place and listed
#   - generated files (GTK settings, kitty/rofi/dunst colours…) are removed
#   - the most recent backup is restored
#   - ~/.config/i3/local/ and ~/.local/share/harbor/backups/ are kept
set -euo pipefail

DATA="${XDG_DATA_HOME:-$HOME/.local/share}/harbor"
MANIFEST="$DATA/manifest"
[ -f "$MANIFEST" ] || { echo "No Harbor install found ($MANIFEST missing)." >&2; exit 1; }

repo=$(sed -n 's/^repo://p' "$MANIFEST")
backup=$(sed -n 's/^backup://p' "$MANIFEST")
printf 'Remove Harbor and restore %s? [y/N] ' "${backup/#$HOME/\~}"
read -r answer
case "$answer" in y|Y|yes) ;; *) echo "Nothing changed."; exit 0 ;; esac

# stop Harbor's daemons — only the ones running from this install, not another user's/HOME's
scripts="${XDG_CONFIG_HOME:-$HOME/.config}/i3/scripts"
pkill -f "^python3 $scripts/harbor watch" 2>/dev/null || true
pkill -f "^python3 $scripts/clipboard.py daemon" 2>/dev/null || true

kept=()
while IFS= read -r line; do
    case "$line" in
        mode:*|backup:*|repo:*) continue ;;
        generated:*)
            f=${line#generated:}
            if [ -f "$f" ] && grep -q "generated by harbor" "$f"; then rm -f -- "$f"; fi
            ;;
        *)
            f=$line
            [ -e "$f" ] || [ -L "$f" ] || continue
            if [ -L "$f" ]; then
                case "$(readlink -- "$f")" in "$repo"/*) rm -f -- "$f" ;; *) kept+=("$f") ;; esac
                continue
            fi
            # a copy: remove only if it still matches the repo file it came from
            src=""
            case "$f" in
                "${XDG_CONFIG_HOME:-$HOME/.config}"/*) src="$repo/config/${f#"${XDG_CONFIG_HOME:-$HOME/.config}/"}" ;;
                "$DATA/wallpapers"/*)                   src="$repo/wallpapers/${f#"$DATA/wallpapers/"}" ;;
            esac
            if [ -n "$src" ] && [ -f "$src" ] && cmp -s -- "$src" "$f"; then rm -f -- "$f"; else kept+=("$f"); fi
            ;;
    esac
done < "$MANIFEST"

restored=0
if [ -d "$backup" ]; then
    while IFS= read -r -d '' f; do
        rel=${f#"$backup/"}
        if [ ! -e "$HOME/$rel" ]; then
            mkdir -p -- "$(dirname "$HOME/$rel")"
            cp -a -- "$f" "$HOME/$rel"
            restored=$((restored + 1))
        fi
    done < <(find "$backup" -type f -print0)
fi
rm -f -- "$MANIFEST"

echo "✓ Harbor removed; restored $restored file(s) from ${backup/#$HOME/\~}"
if [ ${#kept[@]} -gt 0 ]; then
    echo "  Left in place because you changed them:"
    printf '    %s\n' "${kept[@]}"
fi
echo "  Kept: ~/.config/i3/local/ and ~/.local/share/harbor/backups/. Restart i3 to finish."
